[colors]
background = '#f2f2f2'
foreground = '#000000'

cursor_bg = '#3548cf'
cursor_fg = '#f2f2f2'
cursor_border = '#3548cf'

selection_bg = '#dfe3ff'
selection_fg = '#000000'

ansi = ['#ffffff', '#c41541', '#059b1e', '#f8b300', '#2f44d9', '#c2c9ff', '#3548cf', '#363639']
brights = ['#a9aaaf', '#f83f6e', '#29e348', '#ffb700', '#2b43ee', '#c2c9ff', '#a0abff', '#f7f8ff']
