[colors]
background = '#f2f2f2'
foreground = '#000000'

cursor_bg = '#3548cf'
cursor_fg = '#f2f2f2'
cursor_border = '#3548cf'

selection_bg = '#dfe3ff'
selection_fg = '#000000'

ansi = ['#ffffff', '#8c0f0b', '#09720a', '#7f7811', '#546aff', '#3443af', '#3548cf', '#1a1a1a']
brights = ['#2e2e2e', '#a52420', '#138c15', '#999121', '#2d46f8', '#3f78ff', '#9559ff', '#1a1a1a']
