[mgr]
show_hidden = false
[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "linux" }
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "linux" }
]
pdf = [
  { run = 'evince "$@"', orphan = true, for = "linux" }
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" }
]
office = [
  { run = 'libreoffice "$@"', orphan = true, for = "linux" }
]

[open]
rules = [
  # { name = "*/", use = [ "edit", "open" ]},

  { mime = "application/pdf", use = "pdf" },

  { mime = "video/*", use = "play" },

  { mime = "audio/*", use = "play" },

  { mime = "application/oasis.opendocument.*", use = "office" },

]
